# Generated by Django 4.2.3 on 2023-08-15 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber_name', models.CharField(blank=True, max_length=50)),
                ('barber_img', models.ImageField(blank=True, upload_to='barber_img')),
                ('barber_phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('barber_email', models.CharField(blank=True, max_length=50, null=True)),
                ('barber_facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('barber_twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('barber_instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('barber_youtube', models.CharField(blank=True, max_length=50, null=True)),
                ('barber_whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('barber_start_time', models.TimeField(blank=True, null=True)),
                ('barber_end_time', models.TimeField(blank=True, null=True)),
                ('barber_adress', models.CharField(blank=True, max_length=300, null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('is_home', models.BooleanField(blank=True, default=True)),
                ('barber_money', models.IntegerField(default=3)),
                ('interest_rate', models.FloatField(default=2.5)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_success', models.BooleanField(default=False)),
                ('is_success_description', models.CharField(blank=True, max_length=20, null=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.barber', verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber_service', models.CharField(max_length=100)),
                ('service_price', models.IntegerField()),
                ('service_time', models.IntegerField()),
                ('service_img', models.ImageField(upload_to='service_img')),
                ('barber_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sign.barber')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('optional', models.TextField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('service_cost', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('barber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.barber')),
                ('set_service', models.ManyToManyField(blank=True, default=None, to='sign.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
