# Generated by Django 4.2.3 on 2023-08-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=50)),
                ('salon_image', models.ImageField(upload_to='salon/')),
                ('barber', models.ManyToManyField(blank=True, default=None, related_name='barber', to='sign.barber')),
            ],
        ),
    ]
